---
title: "2016BracketPrediction"
author: "Alli Ewald"
date: "March 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(Matrix)
library(stringr)
```

```{r}
source("BasketballRanking.R")
source('MarginPredictionFromCenter.R')



```

```{r}
#Atlantic Coast
#rankedteams %>% filter(State %in% c("MD", "DE", "DC", "NC", "SC", "VA")) %>% select(Team, Index, Rating, Wins, Losses)
#Great Lakes
#rankedteams %>% filter(State %in% c("IL", "IN", "KY", "MI")) %>% select(Team, Index, Rating, Wins, Losses)
#New England
#rankedteams %>% filter(State %in% c("ME", "MA", "NH", "RI", "VT")) %>% select(Team, Index, Rating, Wins, Losses)
#South Central
#rankedteams %>% filter(State %in% c("AR", "CO", "KS", "MO", "OK", "TX", "WY")) %>% filter(`Competition Division`=="Division I") %>% select(Team, Index, Rating, Wins, Losses)
#Southeast
#rankedteams %>% filter(State %in% c("AL", "FL", "GA", "LA", "MS", "TN")) %>% filter(`Competition Division`=="Division I")%>% select(Team, Index, Rating, Wins, Losses)
#rankedteams  %>% filter(`Competition Division`=="Division I")%>% select(Team, Index, Rating, Wins, Losses)

rankedteams <-rankings   %>% 
#  filter(`Competition Level` == "Club") %>% 
  mutate(Ranking=min_rank(desc(Rating)))%>%
  left_join(teams) %>% 
  rename(Index=Label) %>%
  #filter(Index %in% indices) %>%
  arrange( Ranking)# %>% 
  #arrange( order(indices)) %>%
  #mutate(Seed = row_number()) %>% 
  #select(Index, Team, Ranking, Rating, Wins, Losses, )  %>% 
  #knitr::kable()
#rankedteams  %>% filter(`Competition Level` == "Club") %>% select(Team, Index, Rating, Wins, Losses) %>% .$Index
rankedteams
```

```{r}
bids <- 1
indices <- c(1242, 1437, 1274, 1143, 1268, 1112, 1234, 1160, 1163, 1396, 1435,
             1455, 1355, 1218, 1138, 1421, 1122, 1332, 1328, 1401, 1181, 1124,
             1400, 1333, 1386, 1153, 1433, 1320, 1463, 1423, 1453, 1167, 1221,
             1380, 1314, 1462, 1452, 1246, 1231, 1323, 1458, 1425, 1344, 1338,
             1276, 1409, 1151, 1392, 1372, 1451, 1195, 1192, 1438, 1277, 1428,
             1235, 1345, 1371, 1173, 1403, 1139, 1393, 1211, 1114, 1233, 1201,
             1292, 1214


             )
indices <-sort(indices)
#indices <- c(48,155,,,,,54,,,,,140,181,293,132,,)
e <- Rating
#e<-Re(eigen(t(A))$vectors[,1])
#e<-e/sum(e)*length(e)
# possibleTeams <-indices[1:bids]
# cat(possibleTeams, " ")
# team <-bids+1
# possible =TRUE
# while(possible){
#   if(Predict_Margin(A_unnormed, c(0,shares,1),
#                     indices[team],possibleTeams[bids], e)>-4 ){
#     possibleTeams <- indices[1:team]
#     cat(possibleTeams[team], " ")
#     team=team+1
#     if(team > length(indices)){
#       possible = FALSE
#     }
#   } else{
#     possible = FALSE
#   }
# }
#indices <-sort(indices)
rankedteams   %>% 
  
  mutate(Ranking=min_rank(desc(Rating)))%>%
  filter(Index %in% indices) #%>%
#  arrange( Index) %>% 
 # arrange( order(indices)) %>%
  #mutate(Seed = row_number()) %>%  
  #select(Seed, Team, Ranking, Rating, Wins, Losses )  %>% 
  #knitr::kable()

shares <- c(0,Expecteds, 1)
```
```{r}

MOV=diag(rep(0,length(match(indices, teams$Label))))
for( i in 1:(length(match(indices, teams$Label))-1)){
  for(j in (i+1):length(match(indices, teams$Label))){
    MOV[i,j]= Predict_Margin_Meyer(A_unnormed , c(0,Expecteds,1), match(indices[j], teams$Label), match(indices[i], teams$Label), e)
    cat(as.character(teams$Team[match(indices[i], teams$Label)])," ", as.character(teams$Team[match(indices[j], teams$Label)]), ":", MOV[i,j], "\n")
    MOV[j,i]=-MOV[i,j]
  }
}


```




```{r }
require(stringr)
rownames(MOV) <-str_trim(as.character(teams$Team[match(indices, teams$Label)]))
colnames(MOV) <-str_trim(as.character(teams$Team[match(indices, teams$Label)]))
#print(xtable::xtable(MOV), type="html")
MOV
save(MOV, file="FCSTournamentMOV.Rdata")


```

```{r prob}

MOVp=matrix(Expecteds[MaxMOV+MOV], nrow=68, byrow=FALSE)
#vector<-c(k)
prob<-rep(0.5, 2278)
GameID = rep(" ", 2278)

game=1

for(i in 1:(length(indices)-1)){
  for(j in (i+1):length(indices)){
    GameID[game] = paste("2016", indices[i], indices[j], sep='_')
    prob[game] = MOVp[i,j]
    game=game+1
  }
}
  
#forKaggle <- data.frame(GameID, prob) 
#write_csv(forKaggle, "KaggleSubmit2017.csv")


tallscores<-read.csv("NCAATourneyCompactResults.csv")
#names(tgames)<-c("Year","Day","Team1","Score1","Team2","Score2","Home", "OT")
tscores<-subset(tallscores, Season == 2016)

accuracy <- sum(log(MOVp[cbind(match(tscores$LTeamID, indices),match(tscores$WTeamID, indices))]))
accuracy
#accuracy<-(-1/length(tscores)+sum(prob[game]*log10(prob[game]))-(1-prob[game])log10(1-prob[game]))

```